export const ASSETS = {
  pixel9a: "/assets/pixel-9a.png",
  airpods: "/assets/airpods.png",
  keyboard: "/assets/keyboard.png",
  matcha: "/assets/matcha.png",
  figma: "/assets/figma.png",
  react: "/assets/react.png",
  godLike: "/assets/godlike.png",
  rcb: "/assets/rcb.png",
  realMadrid: "/assets/real-madrid.png",
  pokeBall: "/assets/poke-ball.png",
  pokemon: "/assets/pokemon.png",
  pikachu: "/assets/pikachu.png",
  karanAujla: "/assets/karan-aujla.png",
  krsna: "/assets/krsna.png",
  seedheMaut: "/assets/seedhe-maut.png",
  seoul: "/assets/seoul.png",
  controller: "/assets/controller.png",
  passport: "/assets/passport.png",
  rome: "/assets/rome.png",
  istanbul: "/assets/istanbul.png",
  hongKong: "/assets/hongkong.png",
  amsterdam: "/assets/amsterdam.png",
  mumbai: "/assets/mumbai.jpg",
  japanBook1: "/assets/japanbook1.png",
  japanBook2: "/assets/japanbook2.png",
  washiTape: "/assets/watashi-tape.png",
  yen: "/assets/yen.png",

  gum: "/assets/gum.png",
  lighter: "/assets/lighter.png",
  pen: "/assets/pen.png",
  pendrive: "/assets/pendrive.png",
  pins: "/assets/pins.png",
  watch: "/assets/watch.png",
  earPods: "/assets/earpods.png",
  clip1: "/assets/clip1.png",
  clip2: "/assets/clip2.png",
  mouse: "/assets/mouse.png",
  car: "/assets/car.png",
  car2: "/assets/car2.png",
  note: "/assets/note.png",
};

